const RECIPES = [
  {
    id: 1,
    title: "奶油培根蛋烏龍便當",
    subtitle: "Carbonara Style",
    description: "被作者戲稱為連羅馬士兵都會驚訝的美味！奶香濃郁，起司拉絲，一顆生蛋攪下去瞬間升華。",
    category: "便當",
    tags: ["微波料理", "快速", "日式"],
    servings: 1,
    time: "10 分鐘",
    difficulty: "簡單",
    image: "images/carbonara_udon.png",
    ingredients: [
      { name: "冷凍烏龍麵", amount: "1 塊", star: false },
      { name: "牛奶", amount: "2 大匙", star: true },
      { name: "康寶/雞粉（顆粒狀）", amount: "約 1 小匙弱", star: true },
      { name: "蒜泥", amount: "約 1~2 cm", star: true },
      { name: "培根", amount: "約 3 片切段", star: false },
      { name: "起司片", amount: "1 片", star: true },
      { name: "美乃滋", amount: "1 大匙", star: true },
      { name: "黑胡椒", amount: "適量", star: true },
      { name: "生雞蛋", amount: "1 顆（食用前準備）", star: false },
    ],
    steps: [
      "在保鮮盒中放入冷凍烏龍麵，依序疊上培根、起司等所有標註「☆」的調味料。",
      "加熱：微波爐 600W 加熱 4~5 分鐘。",
      "趁熱打入一顆生雞蛋，用力攪拌均勻即可享用！",
    ],
    tips: "剩下的醬汁拌飯也超級好吃。",
  },
  {
    id: 2,
    title: "韓式豬肉泡菜烏龍便當",
    subtitle: "Kimchi Style",
    description: "香辣開胃，是清冰箱的好夥伴。泡菜的酸辣搭配麻油香氣，讓人一口接著一口。",
    category: "便當",
    tags: ["微波料理", "辣", "韓式"],
    servings: 1,
    time: "12 分鐘",
    difficulty: "簡單",
    image: "images/kimchi_udon.png",
    ingredients: [
      { name: "冷凍烏龍麵", amount: "1 塊", star: false },
      { name: "泡菜", amount: "約保鮮盒一半的量", star: false },
      { name: "豬肉片", amount: "約 40~50g", star: false },
      { name: "青蔥", amount: "10g", star: false },
      { name: "麻油", amount: "1 小匙（重口味可用到 3 小匙）", star: true },
      { name: "韓式辣醬", amount: "約一個 100 元硬幣大小", star: true },
      { name: "2倍濃縮麵露", amount: "1 大匙弱", star: true },
      { name: "白芝麻", amount: "適量", star: true },
      { name: "生雞蛋", amount: "1 顆（視喜好添加）", star: false },
    ],
    steps: [
      "在麵上面依序鋪上材料。注意：豬肉片請盡量鋪平不要重疊，確保受熱均勻。",
      "蓋子錯開（留縫隙），600W 微波 6 分鐘。",
      "務必確認豬肉是否全熟，若還有粉紅色請追加加熱。最後可加入蛋黃攪拌。",
    ],
    tips: "不嗜辣的人可省略韓式辣醬。加入蛋黃攪拌後更加濃郁！",
  },
  {
    id: 3,
    title: "鹽味檸檬雞肉丸烏龍便當",
    subtitle: "Chanko-nabe Style",
    description: "清爽系首選，酸甜的檸檬香氣非常解膩。湯頭清澈鮮甜，適合重口味後的解膩之選。",
    category: "便當",
    tags: ["微波料理", "清淡", "日式", "湯"],
    servings: 1,
    time: "12 分鐘",
    difficulty: "簡單",
    image: "images/lemon_chicken_udon.png",
    ingredients: [
      { name: "冷凍烏龍麵", amount: "1 塊", star: false },
      { name: "小白菜漬（或小白菜）", amount: "約 30g", star: false },
      { name: "冷凍雞肉丸", amount: "6 顆", star: false },
      { name: "麵露", amount: "2 小匙", star: true },
      { name: "雞湯粉", amount: "1.5 小匙", star: true },
      { name: "檸檬片", amount: "3 片（怕酸可放 1~2 片）", star: true },
      { name: "蔥花、黑胡椒", amount: "適量", star: true },
      { name: "水", amount: "150ml（加熱前加入）", star: false },
    ],
    steps: [
      "將所有材料堆疊在冷凍麵上。",
      "加入 150ml 的冷開水，蓋子錯開，600W 微波 6 分鐘。",
      "如果不夠熱，請再短時間追加加熱。",
    ],
    tips: "剩下的湯頭加入白飯和起司，做成「起司燉飯」超讚！",
  },
];
