// ============================================================
// 食材標籤分類系統
// ============================================================
const INGREDIENT_TAG_COLORS = {
  主食: { bg: 'rgba(139,92,246,0.2)', border: 'rgba(139,92,246,0.5)', text: '#a78bfa' },
  蛋白質: { bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.4)', text: '#f87171' },
  蔬菜: { bg: 'rgba(34,197,94,0.15)', border: 'rgba(34,197,94,0.4)', text: '#4ade80' },
  乳製品: { bg: 'rgba(251,191,36,0.15)', border: 'rgba(251,191,36,0.4)', text: '#fbbf24' },
  調味料: { bg: 'rgba(232,169,92,0.15)', border: 'rgba(232,169,92,0.4)', text: '#e8a95c' },
  醬汁: { bg: 'rgba(249,115,22,0.15)', border: 'rgba(249,115,22,0.4)', text: '#fb923c' },
  香料: { bg: 'rgba(20,184,166,0.15)', border: 'rgba(20,184,166,0.4)', text: '#2dd4bf' },
  油脂: { bg: 'rgba(161,161,170,0.15)', border: 'rgba(161,161,170,0.4)', text: '#a1a1aa' },
  湯底: { bg: 'rgba(59,130,246,0.15)', border: 'rgba(59,130,246,0.4)', text: '#60a5fa' },
  發酵食品: { bg: 'rgba(217,70,239,0.15)', border: 'rgba(217,70,239,0.4)', text: '#e879f9' },
  水: { bg: 'rgba(56,189,248,0.15)', border: 'rgba(56,189,248,0.4)', text: '#38bdf8' },
};

// ============================================================
// 食譜資料
// ============================================================
const RECIPES = [
  {
    id: 1,
    title: '奶油培根蛋烏龍便當',
    subtitle: 'Carbonara Style',
    description: '被作者戲稱為連羅馬士兵都會驚訝的美味！奶香濃郁，起司拉絲，一顆生蛋攪下去瞬間升華。',
    category: '便當',
    cuisine: '日義融合',
    mealType: '麵條',
    tags: ['微波料理', '快速', '日式', '奶香'],
    servings: 1,
    time: '10 分鐘',
    difficulty: '簡單',
    image: 'images/carbonara_udon.png',
    ingredients: [
      { name: '冷凍烏龍麵', qty: 1, unit: '塊', scalable: true, star: false, tags: ['主食'] },
      { name: '牛奶', qty: 2, unit: '大匙', scalable: true, star: true, tags: ['乳製品'] },
      { name: '康寶/雞粉（顆粒狀）', qty: 1, unit: '小匙弱', scalable: true, star: true, tags: ['調味料'] },
      { name: '蒜泥', qty: 2, unit: 'cm', scalable: true, star: true, tags: ['香料'] },
      { name: '培根', qty: 3, unit: '片', scalable: true, star: false, tags: ['蛋白質'] },
      { name: '起司片', qty: 1, unit: '片', scalable: true, star: true, tags: ['乳製品'] },
      { name: '美乃滋', qty: 1, unit: '大匙', scalable: true, star: true, tags: ['調味料'] },
      { name: '黑胡椒', qty: null, unit: '適量', scalable: false, star: true, tags: ['香料'] },
      { name: '生雞蛋', qty: 1, unit: '顆', scalable: true, star: false, tags: ['蛋白質'] },
    ],
    steps: [
      '在保鮮盒中放入冷凍烏龍麵，依序疊上培根、起司等所有標註「☆」的調味料。',
      '加熱：微波爐 600W 加熱 4~5 分鐘。',
      '趁熱打入一顆生雞蛋，用力攪拌均勻即可享用！',
    ],
    tips: '剩下的醬汁拌飯也超級好吃。',
  },
  {
    id: 2,
    title: '韓式豬肉泡菜烏龍便當',
    subtitle: 'Kimchi Style',
    description: '香辣開胃，是清冰箱的好夥伴。泡菜的酸辣搭配麻油香氣，讓人一口接著一口。',
    category: '便當',
    cuisine: '韓式',
    mealType: '麵條',
    tags: ['微波料理', '辣', '韓式', '發酵'],
    servings: 1,
    time: '12 分鐘',
    difficulty: '簡單',
    image: 'images/kimchi_udon.png',
    ingredients: [
      { name: '冷凍烏龍麵', qty: 1, unit: '塊', scalable: true, star: false, tags: ['主食'] },
      { name: '泡菜', qty: 0.5, unit: '保鮮盒', scalable: true, star: false, tags: ['發酵食品', '蔬菜'] },
      { name: '豬肉片', qty: 50, unit: 'g', scalable: true, star: false, tags: ['蛋白質'] },
      { name: '青蔥', qty: 10, unit: 'g', scalable: true, star: false, tags: ['蔬菜', '香料'] },
      { name: '麻油', qty: 1, unit: '小匙', scalable: true, star: true, tags: ['油脂'] },
      { name: '韓式辣醬', qty: 1, unit: '硬幣大小', scalable: false, star: true, tags: ['醬汁', '調味料'] },
      { name: '2倍濃縮麵露', qty: 1, unit: '大匙弱', scalable: true, star: true, tags: ['醬汁'] },
      { name: '白芝麻', qty: null, unit: '適量', scalable: false, star: true, tags: ['香料'] },
      { name: '生雞蛋', qty: 1, unit: '顆', scalable: true, star: false, tags: ['蛋白質'] },
    ],
    steps: [
      '在麵上面依序鋪上材料。注意：豬肉片請盡量鋪平不要重疊，確保受熱均勻。',
      '蓋子錯開（留縫隙），600W 微波 6 分鐘。',
      '務必確認豬肉是否全熟，若還有粉紅色請追加加熱。最後可加入蛋黃攪拌。',
    ],
    tips: '不嗜辣的人可省略韓式辣醬。加入蛋黃攪拌後更加濃郁！',
  },
  {
    id: 3,
    title: '鹽味檸檬雞肉丸烏龍便當',
    subtitle: 'Chanko-nabe Style',
    description: '清爽系首選，酸甜的檸檬香氣非常解膩。湯頭清澈鮮甜，適合重口味後的解膩之選。',
    category: '便當',
    cuisine: '日式',
    mealType: '麵條',
    tags: ['微波料理', '清淡', '日式', '湯'],
    servings: 1,
    time: '12 分鐘',
    difficulty: '簡單',
    image: 'images/lemon_chicken_udon.png',
    ingredients: [
      { name: '冷凍烏龍麵', qty: 1, unit: '塊', scalable: true, star: false, tags: ['主食'] },
      { name: '小白菜漬（或小白菜）', qty: 30, unit: 'g', scalable: true, star: false, tags: ['蔬菜'] },
      { name: '冷凍雞肉丸', qty: 6, unit: '顆', scalable: true, star: false, tags: ['蛋白質'] },
      { name: '麵露', qty: 2, unit: '小匙', scalable: true, star: true, tags: ['醬汁'] },
      { name: '雞湯粉', qty: 1.5, unit: '小匙', scalable: true, star: true, tags: ['調味料', '湯底'] },
      { name: '檸檬片', qty: 3, unit: '片', scalable: true, star: true, tags: ['香料'] },
      { name: '蔥花', qty: null, unit: '適量', scalable: false, star: true, tags: ['蔬菜', '香料'] },
      { name: '黑胡椒', qty: null, unit: '適量', scalable: false, star: true, tags: ['香料'] },
      { name: '水', qty: 150, unit: 'ml', scalable: true, star: false, tags: ['水'] },
    ],
    steps: [
      '將所有材料堆疊在冷凍麵上。',
      '加入 150ml 的冷開水，蓋子錯開，600W 微波 6 分鐘。',
      '如果不夠熱，請再短時間追加加熱。',
    ],
    tips: '剩下的湯頭加入白飯和起司，做成「起司燉飯」超讚！',
  },
];
